services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aesthetic_backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app